#
# Copyright (C) 2000-2013
# nizvoo (AT) gmail.com
#
CC = cl
CXX = cl
RM = del
CP = copy
BIN = Uart2Uart.exe
SRC = Uart2Uart.c ../comm/ComPortUtils.c
OBJ = Uart2Uart.obj ComPortUtils.obj
CFLAGS = -I../../ -D_UNICODE -DUNICODE /Zc:wchar_t- /O2
WSLIB = 


$(BIN): $(SRC)
	$(CC) $(CFLAGS) $(SRC) $(WSLIB) /Fe$(BIN)

PHONY: clean
clean:
	-$(RM) $(OBJ)
	-$(RM) $(BIN)